server:
  port: 1453
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactiveSpringExample
      username: blacksea
      password: blacksea
      authentication-database: admin
